import { inflateSync, inflateRawSync } from 'node:zlib';

function normalizeBin(v){const x=String(v||'BLACK').toUpperCase();return['BLACK','BLUE','BROWN'].includes(x)?x:'BLACK';}
function todayLondon(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}
function isoDate(y,m,d){return new Date(Date.UTC(Number(y),Number(m)-1,Number(d))).toISOString().slice(0,10);}
function unescapePdfString(s){return String(s||'').replace(/\\([nrtbf()\\])/g,(_,c)=>({n:'\n',r:'\r',t:'\t',b:'\b',f:'\f','(':'(',')':')','\\':'\\'}[c]||c)).replace(/\\([0-7]{1,3})/g,(_,o)=>String.fromCharCode(parseInt(o,8)));}
function textFromPdfBuffer(buffer){const latin=buffer.toString('latin1');const chunks=[latin];const streamRe=/<<(?:.|\n|\r)*?\/Filter\s*\/FlateDecode(?:.|\n|\r)*?>>\s*stream\r?\n/g;let m;while((m=streamRe.exec(latin))){const start=streamRe.lastIndex;const end=latin.indexOf('endstream',start);if(end<0)break;let bytes=buffer.subarray(start,end);while(bytes.length&&[10,13].includes(bytes[bytes.length-1]))bytes=bytes.subarray(0,bytes.length-1);try{chunks.push(inflateSync(bytes).toString('latin1'));}catch{try{chunks.push(inflateRawSync(bytes).toString('latin1'));}catch{}}streamRe.lastIndex=end+9;}const out=[];for(const chunk of chunks){for(const sm of chunk.matchAll(/\((?:\\.|[^\\)])*\)\s*(?:Tj|['"])/g))out.push(unescapePdfString(sm[0].replace(/^\(|\)\s*(?:Tj|['"])$/g,'')));for(const am of chunk.matchAll(/\[(.*?)\]\s*TJ/gs)){for(const sm of am[1].matchAll(/\((?:\\.|[^\\)])*\)/g))out.push(unescapePdfString(sm[0].slice(1,-1)));}for(const hm of chunk.matchAll(/<([0-9A-Fa-f]{4,})>\s*Tj/g)){try{const hex=hm[1];let s='';for(let i=0;i<hex.length;i+=4)s+=String.fromCharCode(parseInt(hex.slice(i,i+4),16));out.push(s);}catch{}}}return (out.join(' ')+' '+chunks.join(' ')).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,' ').replace(/\s+/g,' ');}
function parseDates(text,wanted){const upper=String(text||'').toUpperCase().replace(/\s+/g,' ');const aliases=wanted==='BLACK'?['BLACK BIN','BLACK']:wanted==='BLUE'?['BLUE/GREEN BIN','BLUE BIN','GREEN BIN','BLUE','GREEN']:['BROWN BIN','BROWN'];let section=upper;for(const a of aliases){const i=upper.indexOf(a);if(i>=0){section=upper.slice(i,i+18000);break;}}const found=[];const months={JAN:1,FEB:2,MAR:3,APR:4,MAY:5,JUN:6,JUL:7,AUG:8,SEP:9,SEPT:9,OCT:10,NOV:11,DEC:12,JANUARY:1,FEBRUARY:2,MARCH:3,APRIL:4,JUNE:6,JULY:7,AUGUST:8,SEPTEMBER:9,OCTOBER:10,NOVEMBER:11,DECEMBER:12};let m;const named=/\b(\d{1,2})(?:ST|ND|RD|TH)?\s+(JAN(?:UARY)?|FEB(?:RUARY)?|MAR(?:CH)?|APR(?:IL)?|MAY|JUN(?:E)?|JUL(?:Y)?|AUG(?:UST)?|SEP(?:TEMBER)?|SEPT(?:EMBER)?|OCT(?:OBER)?|NOV(?:EMBER)?|DEC(?:EMBER)?)\s+(20\d{2})\b/g;while((m=named.exec(section)))found.push(isoDate(m[3],months[m[2]],m[1]));const slash=/\b(\d{1,2})[\/.\-](\d{1,2})[\/.\-](20\d{2})\b/g;while((m=slash.exec(section)))found.push(isoDate(m[3],m[2],m[1]));const today=todayLondon();return[...new Set(found)].filter(d=>d>=today).sort().slice(0,2);}

export default async function handler(req){try{const u=new URL(req.url),pdfUrl=u.searchParams.get('pdfUrl'),bin=normalizeBin(u.searchParams.get('bin'));if(!pdfUrl)return new Response(JSON.stringify({error:'Missing PDF URL.'}),{status:400,headers:{'Content-Type':'application/json'}});const target=new URL(pdfUrl);if(target.hostname!=='www.newrymournedown.org')return new Response(JSON.stringify({error:'Invalid council PDF URL.'}),{status:400,headers:{'Content-Type':'application/json'}});const response=await fetch(target.href,{headers:{'User-Agent':'Mozilla/5.0 (compatible; NI-Bin-Guy/1.0)',Accept:'application/pdf,*/*;q=0.8'}});if(!response.ok)throw new Error(`Council PDF returned ${response.status}`);const bytes=Buffer.from(await response.arrayBuffer());const text=textFromPdfBuffer(bytes);const dates=parseDates(text,bin);return new Response(JSON.stringify({matched:dates.length===2,bin,nextTwoCollectionDates:dates,source:target.href,note:dates.length===2?'Two future dates were extracted directly from the council PDF.':'Council PDF opened, but two future dates for the selected bin were not found in its text.',diagnostic:{pdfBytes:bytes.length,textLength:text.length,textSample:text.slice(0,6000)}}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});}catch(e){return new Response(JSON.stringify({matched:false,error:e?.message||'Council PDF parsing failed'}),{status:502,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}}